### PR TITLE
Move sensitive vars to env

### PR DESCRIPTION
**Pull request by hexeth**
This pull request introduces several enhancements to most of the bash scripts, improving its handling of sensitive variables. The changes include:
- Adding a mechanism to load environment variables from an .env file and moving from the bash scripts to that .env file This makes the script more flexible, easier to configure, and obfuscates sensitive data.
- Changes to the README.MD include:
  - Added more detailed descriptions for the requirements, including links to the necessary tools (ntfy.sh).
  - Improved the usage instructions, adding how to set up the .env file and populate the necessary variables.
  - Added a note to remind users to ensure the .env file is in the same directory as the script when cherry picking scripts

This PR has only been tested for radarr and sonarr so far as those are the services I use. Ideally, the other scripts should be tested for all services prior to committing. If any issues are found please let me know and I'll be more than happy to sort them out!

### CODE REVIEW

**Comment by nickexyz** [comment]
Great idea to separate the variables, awesome work!

I'll test the other scripts later and let you know. I'm guessing they will work fine :)
On a first glance, opWnsense_ntfy_icon is misspelled in opnsense.sh and the variables should probably be named opnsense, rather than opensense.

**Comment by nickexyz** [comment]
Other than opensense/opnsense, there are a few small fixes I found:

Since it's not bash I replaced:
```
# load env file
DIR="$(dirname "$0")"
set -o allexport
source "$DIR/.env"
set +o allexport
```
With:
```
# load env file
DIR=$(dirname "$0")
. "$DIR/.env"
```
In opnsense.sh, seems to work fine.
 
radar_api_key in dotenvexample should be radarr_api_key
$ntfy_icon should be $prowlarr_ntfy_icon in prowlarr.sh
$ntfy_icon should be $sabnzbd_ntfy_icon in sabnzbd.sh

If you want to make those fixes I'll merge the PR ASAP
Well done with the changes!

Oh, and I see now how weird ntfy_ntfy_topic looks, that's on me though. I'll clean that up later. :)

**Comment by hexeth** [comment]
Thanks for the review! Ive made all the adjustments requested

**Comment by nickexyz** [comment]
Perfect, thanks!

**Pull request merged**
